/*
Copyright 2022 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tenancy/v1alpha1"
)

// FakeWorkspaceWriteLocks implements WorkspaceWriteLockInterface
type FakeWorkspaceWriteLocks struct {
	Fake *FakeTenancyV1alpha1
}

var workspacewritelocksResource = schema.GroupVersionResource{Group: "tenancy.kcp.dev", Version: "v1alpha1", Resource: "workspacewritelocks"}

var workspacewritelocksKind = schema.GroupVersionKind{Group: "tenancy.kcp.dev", Version: "v1alpha1", Kind: "WorkspaceWriteLock"}

// Get takes name of the workspaceWriteLock, and returns the corresponding workspaceWriteLock object, and an error if there is any.
func (c *FakeWorkspaceWriteLocks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkspaceWriteLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(workspacewritelocksResource, name), &v1alpha1.WorkspaceWriteLock{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceWriteLock), err
}

// List takes label and field selectors, and returns the list of WorkspaceWriteLocks that match those selectors.
func (c *FakeWorkspaceWriteLocks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkspaceWriteLockList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(workspacewritelocksResource, workspacewritelocksKind, opts), &v1alpha1.WorkspaceWriteLockList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkspaceWriteLockList{ListMeta: obj.(*v1alpha1.WorkspaceWriteLockList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkspaceWriteLockList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workspaceWriteLocks.
func (c *FakeWorkspaceWriteLocks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(workspacewritelocksResource, opts))
}

// Create takes the representation of a workspaceWriteLock and creates it.  Returns the server's representation of the workspaceWriteLock, and an error, if there is any.
func (c *FakeWorkspaceWriteLocks) Create(ctx context.Context, workspaceWriteLock *v1alpha1.WorkspaceWriteLock, opts v1.CreateOptions) (result *v1alpha1.WorkspaceWriteLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(workspacewritelocksResource, workspaceWriteLock), &v1alpha1.WorkspaceWriteLock{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceWriteLock), err
}

// Update takes the representation of a workspaceWriteLock and updates it. Returns the server's representation of the workspaceWriteLock, and an error, if there is any.
func (c *FakeWorkspaceWriteLocks) Update(ctx context.Context, workspaceWriteLock *v1alpha1.WorkspaceWriteLock, opts v1.UpdateOptions) (result *v1alpha1.WorkspaceWriteLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(workspacewritelocksResource, workspaceWriteLock), &v1alpha1.WorkspaceWriteLock{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceWriteLock), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkspaceWriteLocks) UpdateStatus(ctx context.Context, workspaceWriteLock *v1alpha1.WorkspaceWriteLock, opts v1.UpdateOptions) (*v1alpha1.WorkspaceWriteLock, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(workspacewritelocksResource, "status", workspaceWriteLock), &v1alpha1.WorkspaceWriteLock{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceWriteLock), err
}

// Delete takes name of the workspaceWriteLock and deletes it. Returns an error if one occurs.
func (c *FakeWorkspaceWriteLocks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(workspacewritelocksResource, name), &v1alpha1.WorkspaceWriteLock{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkspaceWriteLocks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(workspacewritelocksResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkspaceWriteLockList{})
	return err
}

// Patch applies the patch and returns the patched workspaceWriteLock.
func (c *FakeWorkspaceWriteLocks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkspaceWriteLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(workspacewritelocksResource, name, pt, data, subresources...), &v1alpha1.WorkspaceWriteLock{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceWriteLock), err
}
